In [67]:
import pandas as pd
import numpy as np
import datetime
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import requests
import re

## 1. We imported the datasets in this section

In [68]:
#Rainfall dataset
data1 = pd.read_csv("rain.csv")

In [69]:
data1.head()

,State,City,Latitude,Longitude,Onset date,Season end,Date,Season Length Days,Annual Rainfall mm
0,Abia,Aba,5.10,7.35,8-Mar-2017,12-Dec-2017,2017,276,2505
1,Abia,Abiriba,5.70,7.73,15-Mar-2017,7-Dec-2017,2017,263,2220
2,Abia,Arochukwu,5.38,7.92,11-Mar-2017,10-Dec-2017,2017,270,2369
3,Abia,Arochukwu,5.53,7.76,13-Mar-2019,12-Dec-2019,2019,275,2201
4,Abia,Bende,5.55,7.63,14-Mar-2017,8-Dec-2017,2017,266,2289

In [70]:
#Food price dataset
data2 = pd.read_csv("all.csv")

In [71]:
#inflation rate dataset
data3 = pd.read_csv("InflationRates2019.csv")

## 2. Here we try to fish issues and clean them up

Since we will need to merged the dataset, we have to make sure there are some allignment between them. 

>1. First we have make sure the years tally. To do this, we removed 2021 and 2022 from the food price dataset (data2)

>2. We have to make sure the states in each datasets tally. To do this, we use the assert method to check if the list of states in each data set (data1 and data2) are thesame

>3. We have to ...

In [72]:
#removing 2021 and 2022
data2 = data2[~data2['Date'].str.startswith(('2021', '2022'))]

In [73]:
#assert list(data1["State"].unique()) == list(data2["states"].unique())

In [74]:
data1.State.unique()

array(['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
       'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti',
       'Enugu', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina',
       'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun',
       'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
       'Yobe', 'Zamfara', 'FCT', 'River'], dtype=object)

In [75]:
data2.states.unique()

array(['Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti',
       'Enugu', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina',
       'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nassarawa', 'Niger', 'Ogun',
       'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
       'Yobe', 'Zamfara', 'Bayelsa', 'Bauchi', 'Anambra', 'Akwa Ibom',
       'Adamawa', 'Abia', 'Abuja'], dtype=object)

We notices some discrepancy in the spelling of 3 states (`Nasarawa`, `FCT` and `River`)

In [76]:
data1["State"] = data1["State"].str.replace("FCT", "Abuja")
data1.loc[data1['State']== "River", "State"] = "Rivers"
data1.loc[data1['State']== "Nasarawa", "State"] = "Nassarawa"

We corrected the errors/discrepancy, sorted the state columns for the two datasets and assert their similiarity.

In [77]:
data1 = data1.sort_values(by='State')

In [78]:
data2 = data2.sort_values(by='states')

In [79]:
assert list(data1["State"].unique()) == list(data2["states"].unique())

### Now lets scrape some data from the internet

In [80]:
# lets scrape some data online

url = "https://www.distancelatlong.com/country/nigeria/"

page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

#table= soup.find_all('div', class_ ='col-sm-12 col-md-12 col-lg-12')[5]
table = soup.find_all('table', class_ = 'table table-striped setBorder')[2]
headings = table.find_all('th')
titles = [x.text for x in headings]

df = pd.DataFrame(columns = titles)
col_data = table.find_all('tr')
for col in col_data[1:]:
    row_data = col.find_all('td')
    entry = [data.text for data in row_data]
    
  
    length = len(df)
    df.loc[length] = entry

In [81]:
# Some cleanings
df['States'] = df['States'].str.replace(r'\(\d+\)', '')
df['States'] = df['States'].str.strip()

df.loc[df['States']== "Federal Capital Territory", "States"] = "Abuja"

df= df.rename(columns = {"States":"State"})

/var/folders/_9/z4llrcqd0y122r7_nwdcm5900000gn/T/ipykernel_23746/2957932902.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['States'] = df['States'].str.replace(r'\(\d+\)', '')

## Next we want to limit the rainfall dataset (data1) such that only the states are used and not the local goverment.

In [82]:
food_df = data1.copy()

In [83]:
food_df = food_df[["State", "Date", "Season Length Days", "Annual Rainfall mm"]]

In [84]:
mean_df = food_df.pivot_table(index=['State', 'Date'], 
                             values=['Season Length Days', 'Annual Rainfall mm'], aggfunc='mean')

In [85]:
mean_df =mean_df.reset_index()

In [86]:
mean_df["Date"].unique()

array([2017, 2019, 2020])

In [87]:
mean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               111 non-null    object
 1   Date                111 non-null    int64
 2   Annual Rainfall mm  111 non-null    float64
 3   Season Length Days  111 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 3.6+ KB

We observed that 2018 is missing in this data. luckily we were able to download it from the site [Statista](https://www.statista.com/statistics/1264326/annual-rainfall-in-nigeria-by-state/)

In [88]:
seasonal_2018_interpolation = food_df.pivot_table(index=['State'], 
                             values=['Season Length Days'], aggfunc='mean')
inte_df = seasonal_2018_interpolation.reset_index()


# We need just the seasonal length days 

inte_list = inte_df[["Season Length Days"]]

In [89]:
# read in the dataset for 2018 rainfall
df_2018 = pd.read_excel("annual_rainfall_2018.xlsx", sheet_name = "data2")

df_2018["Season Length Days"] = inte_list

In [90]:
#df_2018["Date"] = pd.to_datetime(df_2018['Date'], format='%Y')
#df_2018["Date"] = df_2018["Date"].dt.year

df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                36 non-null     int64
 1   State               36 non-null     object
 2   Annual Rainfall mm  36 non-null     int64
 3   Season Length Days  36 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.2+ KB

In [91]:
new_df = mean_df.merge(df_2018, on=['Date', 'State', 'Annual Rainfall mm', 'Season Length Days'], how='outer', )

/var/folders/_9/z4llrcqd0y122r7_nwdcm5900000gn/T/ipykernel_23746/1337846014.py:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  new_df = mean_df.merge(df_2018, on=['Date', 'State', 'Annual Rainfall mm', 'Season Length Days'], how='outer', )

In [92]:
new_df.isna().sum()

State                 0
Date                  0
Annual Rainfall mm    0
Season Length Days    0
dtype: int64

In [93]:
new_df.Date.unique()

array([2017, 2019, 2020, 2018])

In [94]:
df

          State     Latitude    Longitude
0          Abia  5.532003041  7.486002487
1       Adamawa   10.2703408   13.2700321
2     Akwa Ibom  5.007996056  7.849998524
3       Anambra  6.210433572   7.06999711
4        Bauchi  11.68040977  10.19001339
5         Benue  7.190399596  8.129984089
6         Borno  10.62042279  12.18999467
7   Cross River  4.960406513  8.330023558
8         Delta  5.890427265  5.680004434
9           Edo  6.340477314  5.620008096
10        Ekiti  7.630372741  5.219980834
11        Enugu  6.867034321  7.383362995
12        Abuja  9.083333149  7.533328002
13        Gombe  10.29044293  11.16995357
14          Imo  5.492997053  7.026003588
15       Jigawa   11.7991891  9.350334607
16       Kaduna   11.0799813  7.710009724
17         Kano  11.99997683    8.5200378
18      Katsina   11.5203937  7.320007689
19        Kebbi  12.45041445  4.199939737
20         Kogi  7.800388203  6.739939737
21        Kwara  8.490010192  4.549995889
22        Lagos  6.443261653  3.391531071
23    Nassarawa  8.490423603    8.5200378
24        Niger   10.4003587  5.469939737
25         Ogun  7.160427265  3.350017455
26         Ondo  7.250395934  5.199982054
27         Osun  7.629959329  4.179992634
28          Oyo  7.970016092  3.590002806
29      Plateau  9.929973978  8.890041055
30       Rivers  4.810002257  7.010000772
31       Sokoto  13.06001548  5.240031289
32       Taraba  7.870409769  9.780012572
33         Yobe  11.74899608  11.96600457
34      Zamfara   12.1704057  6.659996296

In [96]:
final_df = new_df.merge(df, on=['State'])

In [97]:
final_df

,State,Date,Annual Rainfall mm,Season Length Days,Latitude,Longitude
0,Abia,2017,2344.193548,269.193548,5.532003041,7.486002487
1,Abia,2019,2176.058824,273.529412,5.532003041,7.486002487
2,Abia,2020,2127.294118,276.764706,5.532003041,7.486002487
3,Abia,2018,2439.000000,272.307692,5.532003041,7.486002487
4,Abuja,2017,1136.117647,200.000000,9.083333149,7.533328002
...,...,...,...,...,...,...
132,Yobe,2018,759.000000,212.764706,11.74899608,11.96600457
133,Zamfara,2017,791.533333,131.733333,12.1704057,6.659996296
134,Zamfara,2019,434.714286,125.714286,12.1704057,6.659996296
135,Zamfara,2020,707.285714,131.142857,12.1704057,6.659996296
136,Zamfara,2018,891.000000,121.955556,12.1704057,6.659996296

In [98]:
data3["year"] =data3.index

In [99]:
data3 = data3.rename(columns = {"Year":"Month", "Month":"All Items (Year on Change)",
                                "All Items (Year on Change)": "All Items (12 Months Avg. Change)",
                               "All Items (12 Months Avg. Change)": "Food (Year on Change)/1",
                                "Food (Year on Change)/1":"Food (12 Months Avg. Change)/1", 
                                "Food (12 Months Avg. Change)/1": "All Items Less Farm Produce (Year on Change)/2",
                               "All Items Less Farm Produce (Year on Change)/2":"All Items Less Farm Produce (12 Months Avg. Change)/2",
                               "All Items Less Farm Produce (12 Months Avg. Change)/2":"All Items Less Farm Produce and Energy (Year on Change)/3"})

In [100]:
#selecting only required columns
data4 = data3[["Month","All Items (Year on Change)", "All Items (12 Months Avg. Change)",
              "Food (12 Months Avg. Change)/1", "Food (12 Months Avg. Change)/1"]]
data5 = data4.reset_index()
data5 = data5.rename(columns = {"index":"Year"})

In [101]:
#Extracting 2017 to 2020 only
data6 = data5.loc[(data5["Year"]>=2017) & (data5["Year"]<=2020)]
data6 = data6.reset_index()
data6 =data6.drop(columns = ["index"])

In [102]:
#splitting the date column into year and month in the food price dataset
data2['Year'] = data2['Date'].str.extract(r'(\d{4})')  
data2['Month'] = data2['Date'].str.extract(r'M(\d+)')

In [103]:
#Dropping irrelevant columns from the food price dataset
data7= data2.copy()
data7 = data7.drop(columns = ["Date", "Unit"])

In [104]:
#converting year and month into integer in the foodprice dataset
data7["Year"] = data7["Year"].astype(int)
data7["Month"] = data7["Month"].astype(int)

In [107]:
data7

        states                          crops       Value  Year  Month
29988     Abia                     Onion bulb  231.095570  2018     12
30122     Abia  Maize grain yellow sold loose  258.950617  2019      4
30123     Abia  Maize grain yellow sold loose  244.631154  2019      5
30124     Abia  Maize grain yellow sold loose  168.518519  2019      6
30125     Abia  Maize grain yellow sold loose  137.847222  2019      7
...        ...                            ...         ...   ...    ...
24783  Zamfara                         Tomato  320.418572  2018      7
24784  Zamfara                         Tomato  341.850253  2018      8
24785  Zamfara                         Tomato  357.238564  2018      9
24778  Zamfara                         Tomato  248.330897  2018      2
24507  Zamfara          Gari white,sold loose  222.524929  2017      3

[23088 rows x 5 columns]

In [108]:
#First merging:merging the food price dataset with the inflation data
merged_df = data7.merge(data5, on=['Year', 'Month'])

In [109]:
#Sort the merged data by state Alphabetically  
merged_df = merged_df.sort_values(by='states')

In [110]:
#Quick renaming of the state and the date columns of rainfall data
data = final_df.rename(columns= {"State": "states", "Date":"Year"})
data.head(50)

,states,Year,Annual Rainfall mm,Season Length Days,Latitude,Longitude
0,Abia,2017,2344.193548,269.193548,5.532003041,7.486002487
1,Abia,2019,2176.058824,273.529412,5.532003041,7.486002487
2,Abia,2020,2127.294118,276.764706,5.532003041,7.486002487
3,Abia,2018,2439.000000,272.307692,5.532003041,7.486002487
4,Abuja,2017,1136.117647,200.000000,9.083333149,7.533328002
5,Abuja,2019,943.333333,198.166667,9.083333149,7.533328002
6,Abuja,2020,1184.166667,198.000000,9.083333149,7.533328002
7,Adamawa,2017,988.750000,181.250000,10.2703408,13.2700321
8,Adamawa,2019,805.000000,184.090909,10.2703408,13.2700321
9,Adamawa,2020,986.954545,182.000000,10.2703408,13.2700321
10,Adamawa,2018,858.000000,199.206897,10.2703408,13.2700321
11,Akwa Ibom,2017,2683.000000,281.714286,5.007996056,7.849998524
12,Akwa Ibom,2019,2440.000000,283.967742,5.007996056,7.849998524
13,Akwa Ibom,2020,2319.612903,286.838710,5.007996056,7.849998524
14,Akwa Ibom,2018,2487.000000,182.566667,5.007996056,7.849998524
15,Anambra,2017,2025.588235,252.941176,6.210433572,7.06999711
16,Anambra,2019,1872.428571,257.333333,6.210433572,7.06999711
17,Anambra,2020,1851.190476,258.571429,6.210433572,7.06999711
18,Anambra,2018,1935.000000,284.723684,6.210433572,7.06999711
19,Bauchi,2017,851.312500,156.437500,11.68040977,10.19001339
20,Bauchi,2019,564.000000,153.600000,11.68040977,10.19001339
21,Bauchi,2020,779.800000,148.950000,11.68040977,10.19001339
22,Bauchi,2018,1111.000000,256.508475,11.68040977,10.19001339
23,Benue,2017,1529.117647,227.352941,7.190399596,8.129984089
24,Benue,2019,1425.565217,232.217391,7.190399596,8.129984089
25,Benue,2020,1510.217391,234.304348,7.190399596,8.129984089
26,Benue,2018,1210.000000,284.461538,7.190399596,8.129984089
27,Borno,2017,792.062500,144.687500,10.62042279,12.18999467
28,Borno,2019,492.285714,137.642857,10.62042279,12.18999467
29,Borno,2020,696.750000,129.857143,10.62042279,12.18999467
30,Borno,2018,562.000000,231.666667,10.62042279,12.18999467
31,Cross River,2017,2214.384615,257.153846,4.960406513,8.330023558
32,Cross River,2019,2217.333333,243.111111,4.960406513,8.330023558
33,Cross River,2020,2046.444444,267.944444,4.960406513,8.330023558
34,Cross River,2018,2599.000000,136.180556,4.960406513,8.330023558
35,Delta,2017,2175.222222,261.611111,5.890427265,5.680004434
36,Delta,2019,2320.000000,275.884615,5.890427265,5.680004434
37,Delta,2020,2084.192308,267.807692,5.890427265,5.680004434
38,Delta,2018,1871.000000,255.959184,5.890427265,5.680004434
39,Edo,2017,1817.846154,244.769231,6.340477314,5.620008096
40,Edo,2019,1822.277778,254.722222,6.340477314,5.620008096
41,Edo,2020,1654.944444,250.388889,6.340477314,5.620008096
42,Ekiti,2017,1474.875000,223.062500,7.630372741,5.219980834
43,Ekiti,2019,1288.375000,223.687500,7.630372741,5.219980834
44,Ekiti,2020,1370.250000,224.937500,7.630372741,5.219980834
45,Ekiti,2018,1409.000000,257.694444,7.630372741,5.219980834
46,Enugu,2017,1857.888889,245.000000,6.867034321,7.383362995
47,Enugu,2019,1743.823529,226.411765,6.867034321,7.383362995
48,Enugu,2020,1696.529412,244.882353,6.867034321,7.383362995
49,Enugu,2018,1834.000000,250.489796,6.867034321,7.383362995

In [112]:
#Second merging: merging the first merged dataset with rainfall dataset
merged_df2 = data.merge(merged_df, on=['states', 'Year'])

merged_df2.shape

(21372, 13)

In [114]:
#Tidying up and renaming the columns
merged_df3 = merged_df2.rename(columns =
                               {"Value":"Price/Kg (Naira)", "All Items (Year on Change)":"inflation_rate(all_item annual)",
                             "All Items (12 Months Avg. Change)":"inflation_rate(all_item monthly avg.)",
                             "Food (Year on Change)/1":"inflation_rate(food_item annual)",
                                "Food (12 Months Avg. Change)/1": "inflation_rate(food_item monthly avg.)"})

In [115]:
price_df = merged_df3.copy()

# Lets explore the new datasets

In [117]:
# Exploring the first few columns 
price_df.states.nunique()

35

In [118]:
# Checking out the columns and enteries as well as data types
price_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21372 entries, 0 to 21371
Data columns (total 13 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   states                                  21372 non-null  object
 1   Year                                    21372 non-null  int64
 2   Annual Rainfall mm                      21372 non-null  float64
 3   Season Length Days                      21372 non-null  float64
 4   Latitude                                21372 non-null  object
 5   Longitude                               21372 non-null  object
 6   crops                                   21372 non-null  object
 7   Price/Kg (Naira)                        21372 non-null  float64
 8   Month                                   21372 non-null  int64
 9   inflation_rate(all_item annual)         21372 non-null  float64
 10  inflation_rate(all_item monthly avg.)   21372 non-null  float64
 11  inflation_rate(food_item monthly avg.)  21372 non-null  float64
 12  inflation_rate(food_item monthly avg.)  21372 non-null  float64
dtypes: float64(7), int64(2), object(4)
memory usage: 2.3+ MB

In [119]:
#Exploring some statistical summaries of the columns
price_df.describe()

,Year,Annual Rainfall mm,Season Length Days,Price/Kg (Naira),Month,inflation_rate(all_item annual),inflation_rate(all_item monthly avg.),inflation_rate(food_item monthly avg.),inflation_rate(food_item monthly avg.)
count,21372.000000,21372.000000,21372.000000,21372.000000,21372.000000,21372.000000,21372.000000,21372.000000,21372.000000
mean,2018.510949,1323.243640,205.079757,260.524091,6.500000,13.349331,13.696058,15.829574,15.829574
std,1.127758,592.500388,52.607765,101.198222,3.452133,2.218527,2.373083,2.126799,2.126799
min,2017.000000,314.000000,109.478261,70.356125,1.000000,11.020000,11.270000,13.340000,13.340000
25%,2017.000000,792.062500,161.636364,192.028717,3.750000,11.370000,11.540000,13.860000,13.860000
50%,2019.000000,1284.937500,214.500000,245.026122,6.500000,12.400000,12.660000,15.360000,15.360000
75%,2020.000000,1718.250000,248.631579,317.034012,9.250000,15.750000,16.440000,17.750000,17.750000
max,2020.000000,2683.000000,288.130435,985.075365,12.000000,18.720000,17.630000,19.620000,19.620000

In [120]:
#Checking out and dropping duplicated values 
price_df.duplicated().sum()
#price_df = price_df.drop_duplicates()

0

In [ ]:
#Assering that there are no more duplicates 
assert price_df.duplicated().sum() ==0

In [ ]:
#There are no missing values 
price_df.isnull().sum()

In [ ]:
# Creating a new column called month name
def map_month(month_num):
    month_names = {1: 'Jan', 2: 'Feb', 3: 'March', 4: 'Apr', 5: 'May', 6: 'Jun', 7: 'Jul',
                  8: 'Aug', 9: 'Sept', 10: 'Oct', 11: 'Nov', 12: 'Dec'}
    return month_names.get(month_num, 'Invalid Month')

# Create a new column with month names
price_df['Month Name'] = price_df['Month'].apply(lambda x: map_month(x))

In [ ]:
price_df['Year'] = price_df.Year.astype(str)

In [ ]:
#Checking the final shape of the dataset
price_df.shape

# Let's commence visualization

In [ ]:
# Checking the number of unique values for the crops

uniques = price_df.crops.unique()
for i, x in enumerate(uniques):
    print(f"{i} -------  {x}")

In [ ]:
# Lets check the rainfall distribution 


fig = px.histogram(price_df["Annual Rainfall mm"],
                   nbins=100, title='Annual rainfall distribution', 
                   labels={'x': 'Rainfall', 'y': 'Frequency'})
fig.show()

In [ ]:
# Let us see the annual rainfall for each year

#fig = px.bar(price_df, x='Year', y='Annual Rainfall mm', title='Year vs Annual Rainfall')

# Show the plot
#fig.show()