In [ ]:
import pandas as pd
import numpy as pd

In [2]:
#Rainfall dataset
data1 = pd.read_csv("rain.csv")

In [3]:
#Food price dataset
data2 = pd.read_csv("all.csv")

In [4]:
#removing 2021 and 2022
data2 = data2[~data2['Date'].str.startswith(('2021', '2022'))]

In [5]:
#data5 = pd.read_csv("exchange_rate.csv")

In [6]:
#inflation rate dataset
data3 = pd.read_csv("InflationRates2019.csv")

In [7]:
data3["year"] =data3.index

In [8]:
data3 = data3.rename(columns = {"Year":"Month", "Month":"All Items (Year on Change)",
                                "All Items (Year on Change)": "All Items (12 Months Avg. Change)",
                               "All Items (12 Months Avg. Change)": "Food (Year on Change)/1",
                                "Food (Year on Change)/1":"Food (12 Months Avg. Change)/1", 
                                "Food (12 Months Avg. Change)/1": "All Items Less Farm Produce (Year on Change)/2",
                               "All Items Less Farm Produce (Year on Change)/2":"All Items Less Farm Produce (12 Months Avg. Change)/2",
                               "All Items Less Farm Produce (12 Months Avg. Change)/2":"All Items Less Farm Produce and Energy (Year on Change)/3"})

In [14]:
#selecting only required columns
data4 = data3[["Month","All Items (Year on Change)", "All Items (12 Months Avg. Change)",
              "Food (12 Months Avg. Change)/1", "Food (12 Months Avg. Change)/1"]]
data5 = data4.reset_index()
data5 = data5.rename(columns = {"index":"Year"})

In [15]:
#Extracting 2017 to 2020 only
data6 = data5.loc[(data5["Year"]>=2017) & (data5["Year"]<=2020)]
data6 = data6.reset_index()
data6 =data6.drop(columns = ["index"])

In [18]:
#splitting the date column into year and month in the food price dataset
data2['Year'] = data2['Date'].str.extract(r'(\d{4})')  
data2['Month'] = data2['Date'].str.extract(r'M(\d+)')

In [21]:
#Dropping irrelevant columns from the food price dataset
data7= data2.copy()
data7 = data7.drop(columns = ["Date", "Unit"])

In [22]:
#converting year and month into integer in the foodprice dataset
data7["Year"] = data7["Year"].astype(int)
data7["Month"] = data7["Month"].astype(int)

In [24]:
#First merging:merging the food price dataset with the inflation data
merged_df = data7.merge(data5, on=['Year', 'Month'])

In [25]:
#Sort the merged data by state Alphabetically  
merged_df = merged_df.sort_values(by='states')

In [26]:
#Quick renaming of the state and the date columns of rainfall data
data1 = data1.rename(columns= {"State": "states", "Date":"Year"})
data1.head()

,states,City,Latitude,Longitude,Onset date,Season end,Year,Season Length Days,Annual Rainfall mm
0,Abia,Aba,5.10,7.35,8-Mar-2017,12-Dec-2017,2017,276,2505
1,Abia,Abiriba,5.70,7.73,15-Mar-2017,7-Dec-2017,2017,263,2220
2,Abia,Arochukwu,5.38,7.92,11-Mar-2017,10-Dec-2017,2017,270,2369
3,Abia,Arochukwu,5.53,7.76,13-Mar-2019,12-Dec-2019,2019,275,2201
4,Abia,Bende,5.55,7.63,14-Mar-2017,8-Dec-2017,2017,266,2289

In [27]:
#Second merging: merging the first merged dataset with rainfall dataset
merged_df2 = data1.merge(merged_df, on=['states', 'Year'])

In [30]:
#Tidying up and renaming the columns
merged_df3 = merged_df2.rename(columns =
                               {"Value":"Price/Kg (Naira)", "All Items (Year on Change)":"inflation_rate(all_item annual)",
                             "All Items (12 Months Avg. Change)":"inflation_rate(all_item monthly avg.)",
                             "Food (Year on Change)/1":"inflation_rate(food_item annual)",
                                "Food (12 Months Avg. Change)/1": "inflation_rate(food_item monthly avg.)"}) 
                                
merged_df4 = merged_df3.drop(columns = ["Onset date", "Season end"])

In [34]:
price_df = merged_df4.copy()

# Lets explore the new datasets

In [38]:
# Exploring the first few columns 
price_df.head()

,states,City,Latitude,Longitude,Year,Season Length Days,Annual Rainfall mm,crops,Price/Kg (Naira),Month,inflation_rate(all_item annual),inflation_rate(all_item monthly avg.),inflation_rate(food_item monthly avg.),inflation_rate(food_item monthly avg.)
0,Abia,Aba,5.1,7.35,2017,276,2505,"Gari white,sold loose",286.956522,3,17.26,17.32,16.60,16.60
1,Abia,Aba,5.1,7.35,2017,276,2505,"Gari white,sold loose",320.385281,12,15.37,16.50,19.55,19.55
2,Abia,Aba,5.1,7.35,2017,276,2505,Beans:white black eye. sold loose,435.135135,12,15.37,16.50,19.55,19.55
3,Abia,Aba,5.1,7.35,2017,276,2505,"Beans brown,sold loose",471.428571,12,15.37,16.50,19.55,19.55
4,Abia,Aba,5.1,7.35,2017,276,2505,Rice Medium Grained,348.787879,12,15.37,16.50,19.55,19.55

In [39]:
# Checking out the columns and enteries as well as data types
price_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 328224 entries, 0 to 328223
Data columns (total 14 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   states                                  328224 non-null  object
 1   City                                    328224 non-null  object
 2   Latitude                                328224 non-null  float64
 3   Longitude                               328224 non-null  float64
 4   Year                                    328224 non-null  int64
 5   Season Length Days                      328224 non-null  int64
 6   Annual Rainfall mm                      328224 non-null  int64
 7   crops                                   328224 non-null  object
 8   Price/Kg (Naira)                        328224 non-null  float64
 9   Month                                   328224 non-null  int64
 10  inflation_rate(all_item annual)         328224 non-null  float64
 11  inflation_rate(all_item monthly avg.)   328224 non-null  float64
 12  inflation_rate(food_item monthly avg.)  328224 non-null  float64
 13  inflation_rate(food_item monthly avg.)  328224 non-null  float64
dtypes: float64(7), int64(4), object(3)
memory usage: 37.6+ MB

In [40]:
#Exploring some statistical summaries of the columns
price_df.describe()

,Latitude,Longitude,Year,Season Length Days,Annual Rainfall mm,Price/Kg (Naira),Month,inflation_rate(all_item annual),inflation_rate(all_item monthly avg.),inflation_rate(food_item monthly avg.),inflation_rate(food_item monthly avg.)
count,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000,328224.000000
mean,8.634297,7.315846,2018.767586,204.238593,1325.911597,256.687249,6.500000,13.526283,13.318399,15.220042,15.220042
std,2.644012,2.487876,1.207816,56.877733,639.068463,103.555148,3.452058,2.251461,2.502547,1.949706,1.949706
min,4.300000,2.810000,2017.000000,90.000000,342.000000,70.356125,1.000000,11.020000,11.270000,13.340000,13.340000
25%,6.430000,5.440000,2017.000000,147.000000,772.000000,186.989917,3.750000,11.400000,11.400000,13.620000,13.620000
50%,7.925000,7.270000,2019.000000,220.000000,1293.500000,238.990000,6.500000,12.400000,11.800000,14.330000,14.330000
75%,11.305000,8.540000,2020.000000,252.000000,1829.750000,311.680912,9.250000,15.900000,16.500000,16.170000,16.170000
max,13.730000,14.560000,2020.000000,298.000000,3029.000000,985.075365,12.000000,18.720000,17.630000,19.550000,19.550000

In [44]:
#Checking out and dropping duplicated values 
price_df.duplicated().sum()
price_df = price_df.drop_duplicates()

In [47]:
#Assering that there are no more duplicates 
assert price_df.duplicated().sum() ==0

In [43]:
#There are no missing values 
price_df.isnull().sum()

states                                    0
City                                      0
Latitude                                  0
Longitude                                 0
Year                                      0
Season Length Days                        0
Annual Rainfall mm                        0
crops                                     0
Price/Kg (Naira)                          0
Month                                     0
inflation_rate(all_item annual)           0
inflation_rate(all_item monthly avg.)     0
inflation_rate(food_item monthly avg.)    0
inflation_rate(food_item monthly avg.)    0
dtype: int64

In [48]:
#Checking the final shape of the dataset
price_df.shape

(328068, 14)

# Let's commence visualization